# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe9d40b8341d973c8654e60c2509cab3d05a71498fd6afe4c8b344bde63428d8c3ed43134cd440fd421d7f469b31e2e8905a302732216043af60d368c08ef318

test:
  secret_key_base: 5c87ada8e65a5c80f9aad651736908756bb75c43ee3d4d089206864ff032097ed1980be6fea25a395e35f080f42de307a5edba5beb70f61775a1f5b6d1200258

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
